spring:
  application:
    name: Task
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:33333/postgres
    username: rady
    password: task_1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081

springdoc:
  swagger-ui:
    operations-sorter: alpha
    try-it-out-enabled: true
  api-docs:
    resolve-schema-properties: true
  show-actuator: false
  default-flat-param-object: true
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

jwt:
  secret: 3f8a9b2c7d1e4f6a0b3c9d2e5f8a1b4c7d0e3f6a9b2c5d8e1f4a7b0c3d6e9f2a5b8c1d4e7f0a3b6c9d2e5f8a1b4c
  expiration: 86400000
