spring.application.name=Task
server.port=8081
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.tryItOutEnabled=true
jwt.secret=verystrongjwtsecretkeythatishardtotrickyousuperlong

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:33333/postgres
spring.datasource.username=rady
spring.datasource.password=task_1234
spring.jpa.hibernate.ddl-auto=update
distributionUrl=https\://services.gradle.org/distributions/gradle-8.8-bin.zip
