{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-test",
    "version": "6.2.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.8"
          }
        }
      ],
      "files": [
        {
          "name": "spring-test-6.2.8.jar",
          "url": "spring-test-6.2.8.jar",
          "size": 1024684,
          "sha512": "67347de9eaa3536fe4672f86cc5cf1b2ace9a64e694cdb4f018e6a0cf162e120e5db2ffbbd1420c98888932698aa33f7bc245957f88afcd8b45db78ff3dbb0c1",
          "sha256": "e8d95e8274c6db3c6ad696668474b80b45b6b1172fffc894d0680e08d5d96e74",
          "sha1": "f7a691aa541ec9299fdeb4d2d9a61b4c821abcf2",
          "md5": "f65912345785ae107bb38e74d6a4c594"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.8"
          }
        }
      ],
      "files": [
        {
          "name": "spring-test-6.2.8.jar",
          "url": "spring-test-6.2.8.jar",
          "size": 1024684,
          "sha512": "67347de9eaa3536fe4672f86cc5cf1b2ace9a64e694cdb4f018e6a0cf162e120e5db2ffbbd1420c98888932698aa33f7bc245957f88afcd8b45db78ff3dbb0c1",
          "sha256": "e8d95e8274c6db3c6ad696668474b80b45b6b1172fffc894d0680e08d5d96e74",
          "sha1": "f7a691aa541ec9299fdeb4d2d9a61b4c821abcf2",
          "md5": "f65912345785ae107bb38e74d6a4c594"
        }
      ]
    }
  ]
}
